import type {
  Approval,
  Event,
  OrganizerProfile,
  Pass,
  ReportMetric,
  UserProfile,
  Venue,
} from "./types";

export const venues: Venue[] = [
  {
    id: "casa-classico",
    name: "Casa Classico",
    area: "Davao City",
    address: "Casa Classico, Manga St., Tugbok, Davao City",
    mapLink: "https://waze.com/ul?q=Casa%20Classico%20Davao%20City",
    capacityNote: "Small recurring tambike spot for coffee, parking, and casual rider hangouts.",
    status: "APPROVED",
    houseRules: ["Park in assigned areas", "No revving", "Respect cafe guests"],
  },
  {
    id: "shell-pugon",
    name: "Shell Pugon",
    area: "Antipolo",
    address: "Shell Pugon, City of Antipolo, Rizal",
    mapLink: "https://waze.com/ul?q=Shell%20Pugon%20Antipolo",
    capacityNote: "Meetup point for charity and Marilaque-bound ride groups.",
    status: "APPROVED",
    houseRules: ["Keep pumps and driveway clear", "Stage by batch", "No revving"],
  },
  {
    id: "clark-international-speedway",
    name: "Clark International Speedway",
    area: "Angeles City",
    address: "Clark International Speedway, Angeles City, Pampanga",
    mapLink: "https://waze.com/ul?q=Clark%20International%20Speedway",
    capacityNote: "Closed-course track venue with paddock and technical support areas.",
    status: "APPROVED",
    houseRules: ["Complete riding gear required", "Track staff controls entry", "Follow paddock flow"],
  },
  {
    id: "san-marcelino-zambales",
    name: "San Marcelino Ride Base",
    area: "Zambales",
    address: "San Marcelino, Zambales",
    mapLink: "https://waze.com/ul?q=San%20Marcelino%20Zambales",
    capacityNote: "Municipality-level meetup marker for long-ride coordination.",
    status: "APPROVED",
    houseRules: ["Arrive fueled", "Confirm emergency contacts", "Depart by ride marshal signal"],
  },
  {
    id: "koronadal-city-hall",
    name: "Koronadal City Hall Ground",
    area: "Koronadal",
    address: "Koronadal City Hall Ground, Koronadal City, South Cotabato",
    mapLink: "https://waze.com/ul?q=Koronadal%20City%20Hall%20Ground",
    capacityNote: "Event ground for multi-day endurance ride registration and dispatch.",
    status: "APPROVED",
    houseRules: ["Check in before route briefing", "Respect slot limits", "No unsanctioned departures"],
  },
  {
    id: "tarlac-circuit-hill",
    name: "Tarlac Circuit Hill",
    area: "San Jose, Tarlac",
    address: "Tarlac Circuit Hill, San Jose, Tarlac",
    mapLink: "https://waze.com/ul?q=Tarlac%20Circuit%20Hill",
    capacityNote: "Circuit venue for race weekends and spectator check-in.",
    status: "APPROVED",
    houseRules: ["Observe pit lane boundaries", "Follow marshal instructions", "No access to hot track"],
  },
  {
    id: "ic3-cebu",
    name: "IC3 Convention Center Cebu",
    area: "Cebu City",
    address: "IC3 Convention Center, Cebu City",
    mapLink: "https://waze.com/ul?q=IC3%20Convention%20Center%20Cebu",
    capacityNote: "Indoor expo venue suited for brand booths, launches, and rider meetups.",
    status: "APPROVED",
    houseRules: ["Use assigned entrances", "Follow booth queueing", "No engine start inside halls"],
  },
  {
    id: "cue-spot-cafe-malabon",
    name: "5R Cue'Spot Cafe",
    area: "Malabon",
    address: "5R Cue'Spot Cafe, Malabon",
    mapLink: "https://waze.com/ul?q=5R%20Cue%27Spot%20Cafe%20Malabon",
    capacityNote: "Cafe and billiards spot for open tambike nights and casual motorcycle meetups.",
    status: "APPROVED",
    houseRules: ["No engine revving", "No slippers", "Support the venue", "Clean as you go"],
  },
  {
    id: "agojo-lifestyle-strip",
    name: "Agojo The Lifestyle Strip",
    area: "Calamba, Laguna",
    address: "Agojo The Lifestyle Strip, Calamba, Laguna",
    mapLink: "https://waze.com/ul?q=Agojo%20The%20Lifestyle%20Strip%20Calamba%20Laguna",
    capacityNote: "Lifestyle strip suitable for club tambike nights and member onboarding.",
    status: "APPROVED",
    houseRules: ["Keep parking orderly", "Respect nearby businesses", "No revving"],
  },
  {
    id: "swabz-taytay",
    name: "Swabz Taytay",
    area: "Taytay, Rizal",
    address: "Swabz Taytay, Taytay, Rizal",
    mapLink: "https://waze.com/ul?q=Swabz%20Taytay%20Rizal",
    capacityNote: "Classic bike tambike venue with local moto shop activity and raffle programming.",
    status: "APPROVED",
    houseRules: ["Park classic bikes by batch", "Keep shop access open", "No revving"],
  },
  {
    id: "bros-brew-laoag",
    name: "Bro's Brew Cafe",
    area: "Laoag City",
    address: "Bro's Brew Cafe, Brgy. 45 Tangid, Bypass Road, Laoag City, Ilocos Norte",
    mapLink: "https://waze.com/ul?q=Bro%27s%20Brew%20Cafe%20Laoag%20City",
    capacityNote: "Coffee stop for classic motorcycle tambike nights in Laoag.",
    status: "APPROVED",
    houseRules: ["Classic motorcycles prioritized", "No revving", "Respect cafe guests"],
  },
  {
    id: "kape-mo-to-tagaytay",
    name: "Kape Mo-To Tagaytay",
    area: "Tagaytay",
    address: "Kape Mo-To Tagaytay, Petron Tagaytay Motorist Service Station, Aguinaldo Highway, Tagaytay",
    mapLink: "https://waze.com/ul?q=Kape%20Mo-To%20Tagaytay",
    capacityNote: "Motorcycle coffee stop for brand-led tambike meetups.",
    status: "APPROVED",
    houseRules: ["Park in assigned areas", "No revving", "Respect station traffic"],
  },
  {
    id: "fullprint-manila-cafe",
    name: "FullPrint Manila Cafe",
    area: "Paranaque",
    address: "FullPrint Manila Cafe, G/F Kawayan Building, Parqal, Aseana City, Paranaque",
    mapLink: "https://waze.com/ul?q=FullPrint%20Manila%20Cafe%20Parqal%20Paranaque",
    capacityNote: "Cafe-front rider meetup venue with morning food and brand partner activity.",
    status: "APPROVED",
    houseRules: ["Keep storefront clear", "Stage scooters and motorcycles safely", "Respect cafe guests"],
  },
  {
    id: "dayo-specialty-coffee",
    name: "Dayo Specialty Coffee",
    area: "Quezon City",
    address: "Dayo Specialty Coffee, King Ferdinand, Katipunan, Quezon City",
    mapLink: "https://waze.com/ul?q=Dayo%20Specialty%20Coffee%20Katipunan%20Quezon%20City",
    capacityNote: "Coffee meetup spot for cross-club tambike nights and cause-based rider gatherings.",
    status: "APPROVED",
    houseRules: ["No littering", "No burnouts", "No aggressive revving", "Respect fellow riders"],
  },
  {
    id: "helmet-garage-cainta",
    name: "The Helmet Garage",
    area: "Cainta, Rizal",
    address: "The Helmet Garage, Cainta, Rizal",
    mapLink: "https://waze.com/ul?q=The%20Helmet%20Garage%20Cainta",
    capacityNote: "Moto shop tambike venue suited for club chapters, raffle registration, and safe parking.",
    status: "APPROVED",
    houseRules: ["No revving", "No littering", "No burnouts or wheelies", "No aggressive driving"],
  },
  {
    id: "mactan-town-center",
    name: "Mactan Town Center",
    area: "Lapu-Lapu City",
    address: "Mactan Town Center, Lapu-Lapu City, Cebu",
    mapLink: "https://waze.com/ul?q=Mactan%20Town%20Center%20Lapu-Lapu%20City%20Cebu",
    capacityNote: "Open commercial venue for Cebu club tambike nights and chapter rollups.",
    status: "APPROVED",
    houseRules: ["No pops and bangs", "No slippers", "No loitering", "Respect the venue"],
  },
  {
    id: "antipolo-endurance-start",
    name: "Antipolo City Endurance Start",
    area: "Antipolo City",
    address: "Antipolo City, Rizal",
    mapLink: "https://waze.com/ul?q=Antipolo%20City%20Rizal",
    capacityNote: "Start and finish marker for endurance ride registration, briefing, and batch dispatch.",
    status: "APPROVED",
    houseRules: ["Attend rider briefing", "Depart by batch", "No racing", "Respect marshal instructions"],
  },
  {
    id: "san-pablo-convention-center",
    name: "San Pablo Convention Center",
    area: "San Pablo City",
    address: "San Pablo Convention Center, San Pablo City, Laguna",
    mapLink: "https://waze.com/ul?q=San%20Pablo%20Convention%20Center%20Laguna",
    capacityNote: "Convention venue for moto expo booths, club meets, custom showcases, and live programming.",
    status: "APPROVED",
    houseRules: ["Use assigned entrances", "Follow booth queueing", "No engine start inside halls"],
  },
  {
    id: "wao-race-ground",
    name: "Wao Race Ground",
    area: "Wao, Lanao del Sur",
    address: "Race venue, Wao, Lanao del Sur",
    mapLink: "https://waze.com/ul?q=Wao%20Lanao%20del%20Sur%20Race%20Ground",
    capacityNote: "Outdoor motocross race site for festival race programming, team staging, and spectator control.",
    status: "APPROVED",
    houseRules: ["Use assigned spectator areas", "Follow marshal instructions", "No access to race track"],
  },
];

export const organizers: OrganizerProfile[] = [
  {
    id: "cafe-classico",
    displayName: "Cafe Classico Davao",
    type: "Cafe tambike host",
    fbLink: "facebook.com/share/1CpR9D1nwL",
    verificationStatus: "APPROVED",
    pastEvents: 6,
  },
  {
    id: "arai-hjc-riders",
    displayName: "ARAI / HJC Riders PH",
    type: "Helmet-user charity ride community",
    fbLink: "facebook.com/groups/helmetridersph",
    verificationStatus: "APPROVED",
    pastEvents: 2,
  },
  {
    id: "ducati-access-plus",
    displayName: "Ducati Philippines / Access Plus",
    type: "Brand and track organizer",
    fbLink: "facebook.com/DucatiPhilippines",
    verificationStatus: "APPROVED",
    pastEvents: 14,
  },
  {
    id: "republik-riders",
    displayName: "Republik Riders Club",
    type: "Motorcycle charity ride club",
    fbLink: "facebook.com/republikridersclub",
    verificationStatus: "APPROVED",
    pastEvents: 5,
  },
  {
    id: "mandirigma-endutour",
    displayName: "Mandirigma Endutour",
    type: "Endurance ride organizer",
    fbLink: "facebook.com/mandirigmaendutour",
    verificationStatus: "APPROVED",
    pastEvents: 4,
  },
  {
    id: "motoir-ph",
    displayName: "MotoIR Philippines",
    type: "Motorcycle race organizer",
    fbLink: "facebook.com/motoirph",
    verificationStatus: "APPROVED",
    pastEvents: 24,
  },
  {
    id: "makina-moto",
    displayName: "Makina Moto",
    type: "Motorcycle expo organizer",
    fbLink: "facebook.com/makinamotoph",
    verificationStatus: "APPROVED",
    pastEvents: 12,
  },
  {
    id: "dsboys-tambike",
    displayName: "DSBoys / LSTRDBoys / Valenzuela Elite",
    type: "Open motorcycle tambike host",
    fbLink: "facebook.com/share/p/18hS89YSs2",
    verificationStatus: "APPROVED",
    pastEvents: 3,
  },
  {
    id: "boys-underbone-laguna",
    displayName: "Boys of Underbone Laguna",
    type: "Underbone club tambike host",
    fbLink: "facebook.com/boysofunderbonelaguna",
    verificationStatus: "APPROVED",
    pastEvents: 2,
  },
  {
    id: "swabz-classic-motoparts",
    displayName: "Swabz Classic Motoparts",
    type: "Classic bike shop tambike host",
    fbLink: "facebook.com/swabzclassicmotoparts",
    verificationStatus: "APPROVED",
    pastEvents: 4,
  },
  {
    id: "yloco-bandits",
    displayName: "Yloco Bandits Classic Motorcycle",
    type: "Classic motorcycle community",
    fbLink: "facebook.com/ylocobandits",
    verificationStatus: "APPROVED",
    pastEvents: 5,
  },
  {
    id: "motor-ace-bmw",
    displayName: "Motor Ace BMW Motorrad",
    type: "Brand-led tambike host",
    fbLink: "facebook.com/MotorAceBMW",
    verificationStatus: "APPROVED",
    pastEvents: 6,
  },
  {
    id: "fullprint-manila",
    displayName: "FullPrint Manila",
    type: "Cafe and rider meetup host",
    fbLink: "facebook.com/FullPrintManila",
    verificationStatus: "APPROVED",
    pastEvents: 3,
  },
  {
    id: "boys-of-garage",
    displayName: "Boys of Garage",
    type: "Cross-club tambike host",
    fbLink: "facebook.com/boysofgarage",
    verificationStatus: "APPROVED",
    pastEvents: 3,
  },
  {
    id: "ccph-upper-east",
    displayName: "CCPH Upper East",
    type: "Motorcycle chapter tambike host",
    fbLink: "facebook.com/ccphuppereast",
    verificationStatus: "APPROVED",
    pastEvents: 2,
  },
  {
    id: "ccph-cebu",
    displayName: "CCPH Cebu",
    type: "Cebu motorcycle chapter host",
    fbLink: "facebook.com/ccphcebu",
    verificationStatus: "APPROVED",
    pastEvents: 3,
  },
  {
    id: "antipolo-endurance-challenge",
    displayName: "Antipolo City Motorcycle Endurance Challenge",
    type: "Endurance ride organizer",
    fbLink: "facebook.com/ACMEC600",
    verificationStatus: "APPROVED",
    pastEvents: 2,
  },
  {
    id: "laguna-moto-fest",
    displayName: "Laguna Moto Fest",
    type: "Regional moto expo organizer",
    fbLink: "facebook.com/LagunaMotoFest",
    verificationStatus: "APPROVED",
    pastEvents: 1,
  },
  {
    id: "ngo-philippines",
    displayName: "NGO Philippines",
    type: "Streetbike drag race organizer",
    fbLink: "facebook.com/ngophilippines",
    verificationStatus: "APPROVED",
    pastEvents: 6,
  },
  {
    id: "mindanao-wide-motocross",
    displayName: "Mindanao Wide Motocross",
    type: "Motocross race organizer",
    fbLink: "facebook.com/share/p/1F3VZHwKPq",
    verificationStatus: "APPROVED",
    pastEvents: 2,
  },
];

export const mockUsers: UserProfile[] = [
  {
    id: "user-mina-rider",
    displayName: "Mina Rider",
    email: "mina.rider@example.com",
    role: "rider",
    verificationStatus: "UNVERIFIED",
    area: "Marikina",
    bikeModel: "Yamaha Mio Gear",
    clubName: "Weekend Tambike Crew",
    joinedAt: "July 2, 2026",
  },
  {
    id: "user-marco-organizer",
    displayName: "Marco Organizer",
    email: "marco.organizer@example.com",
    role: "organizer",
    verificationStatus: "APPROVED",
    area: "Antipolo",
    bikeModel: "Honda CB650R",
    clubName: "ARAI / HJC Riders PH",
    joinedAt: "June 18, 2026",
    organizerProfileId: "arai-hjc-riders",
  },
  {
    id: "user-ana-venue",
    displayName: "Ana Venue",
    email: "ana.venue@example.com",
    role: "venue",
    verificationStatus: "APPROVED",
    area: "Antipolo",
    joinedAt: "June 24, 2026",
    venueId: "shell-pugon",
  },
  {
    id: "user-tambike-ops",
    displayName: "Tambike Ops",
    email: "ops@tambike.example",
    role: "admin",
    verificationStatus: "APPROVED",
    area: "Metro Manila",
    joinedAt: "June 1, 2026",
  },
];

export const demoEvents: Event[] = [
  {
    id: "tambike-cafe-classico",
    title: "Tambike at Cafe Classico",
    type: "Tambike",
    status: "PUBLISHED",
    organizerId: "cafe-classico",
    venueId: "casa-classico",
    poster: "/demo/poster-tambike-cafe-classico.jpg",
    date: "Every Saturday",
    time: "6:00 PM - 8:00 PM",
    area: "Davao City",
    shortDescription:
      "A recurring Saturday tambike for classic bikes, coffee, stories, and relaxed rider hangouts.",
    whatHappens:
      "Riders arrive direct at Casa Classico, park, check in, grab coffee, talk bikes, and hang out without a ride-out or formal program.",
    going: 48,
    interested: 132,
    expectedRiders: 55,
    perkPreview: "10% coffee discount",
    tags: ["Tambike", "Coffee", "Classic bikes", "No ride-out"],
    riskFlags: ["Evening meetup", "Venue parking", "Coffee discount"],
    rules: ["Helmet required", "No revving", "Respect cafe guests", "Park in assigned areas"],
    perks: [
      {
        id: "classic-coffee-discount",
        type: "Discount",
        description: "10% coffee discount for classic motorcycle owners from 6 PM to 8 PM",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/RwX2gPAndM/tambike-at-cafe-classico-every-saturday",
    sourceNote: "Event name, recurring Saturday tambike format, venue, time, and coffee discount from Bike Night Asia listing.",
  },
  {
    id: "motoir-national-round-5",
    title: "MotoIR National Round 5",
    type: "Race",
    status: "PUBLISHED",
    organizerId: "motoir-ph",
    venueId: "tarlac-circuit-hill",
    poster: "/demo/poster-motoir-round-5.jpg",
    date: "Sat · Sep 19, 2026",
    time: "9:00 AM - Sep 20 11:00 PM",
    area: "San Jose, Tarlac",
    shortDescription:
      "MotoIR Motul National Championship Round 5 race weekend at Tarlac Circuit Hill.",
    whatHappens:
      "Riders, teams, and spectators check in at the circuit, follow paddock access rules, and track the schedule for race heats across the weekend.",
    going: 84,
    interested: 226,
    expectedRiders: 170,
    perkPreview: "Race weekend spectator pass",
    tags: ["Race", "Circuit", "MotoIR", "Tarlac", "Spectator pass"],
    riskFlags: ["Race event", "Circuit venue", "Pit lane access", "Schedule subject to change"],
    rules: ["Follow marshal instructions", "No hot-track access", "Stay outside pit lane barriers", "Respect posted schedule changes"],
    perks: [
      {
        id: "motoir-round-5-spectator-pass",
        type: "Pass",
        description: "QR spectator pass for MotoIR Round 5 weekend entry checks",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/4DnB0GJp5m/motoir-motul-national-championship-2026-round-5",
    sourceNote: "Round 5 dates, Tarlac Circuit Hill venue, race calendar context, and poster from Bike Night Asia listing.",
  },
  {
    id: "motul-motoir-youth-cup-15-16",
    title: "Motul MotoIR Youth Cup Races 15-16",
    type: "Race",
    status: "PUBLISHED",
    organizerId: "motoir-ph",
    venueId: "tarlac-circuit-hill",
    poster: "/demo/poster-motoir-youth-cup-15-16.jpg",
    date: "Sat · Oct 24, 2026",
    time: "9:00 AM - Oct 25 11:00 PM",
    area: "San Jose, Tarlac",
    shortDescription:
      "Final MotoIR Youth Cup weekend for the 2026 calendar with youth race rounds 15 and 16.",
    whatHappens:
      "Youth race teams check in, verify class assignments, stage in paddock lanes, and run the final race weekend under circuit marshal control.",
    going: 63,
    interested: 184,
    expectedRiders: 120,
    perkPreview: "Youth race paddock watchlist",
    tags: ["Race", "Youth Cup", "MotoIR", "Tarlac", "Circuit"],
    riskFlags: ["Youth race event", "Circuit venue", "Paddock access", "Schedule subject to change"],
    rules: ["Follow marshal instructions", "No hot-track access", "Respect paddock lanes", "Use assigned spectator areas"],
    perks: [
      {
        id: "youth-cup-watchlist",
        type: "Watchlist",
        description: "Checked-in spectators can follow youth cup race updates from the event page",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/WaXl8WAXVk/motul-motoir-youth-cup-2026-race-15-16",
    sourceNote: "Race 15-16 dates, Tarlac Circuit Hill venue, schedule-note context, and poster from Bike Night Asia listing.",
  },
  {
    id: "petron-sgp-round-3",
    title: "Petron SGP Round 3",
    type: "Race",
    status: "PUBLISHED",
    organizerId: "motoir-ph",
    venueId: "tarlac-circuit-hill",
    poster: "/demo/poster-petron-sgp-round-3.jpg",
    date: "Sun · Aug 16, 2026",
    time: "9:00 AM - 11:00 PM",
    area: "San Jose, Tarlac",
    shortDescription:
      "Petron Sprint Scooter Grand Prix Championship Round 3 at Tarlac Circuit Hill.",
    whatHappens:
      "Scooter racers and spectators check in at the circuit, follow the posted race calendar, and receive updates if the schedule shifts.",
    going: 77,
    interested: 205,
    expectedRiders: 135,
    perkPreview: "Scooter GP race access",
    tags: ["Race", "Scooter GP", "Petron", "Tarlac", "Circuit"],
    riskFlags: ["Race event", "Circuit venue", "Schedule subject to change", "Spectator crowd"],
    rules: ["Follow marshal instructions", "Stay outside hot-track areas", "Respect paddock boundaries", "Use assigned spectator areas"],
    perks: [
      {
        id: "petron-sgp-race-access",
        type: "Pass",
        description: "QR race access pass for Sprint Scooter GP Round 3 spectators",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/EjX9adMXvk/petron-sprint-scooter-grand-prix-sgp-championship-2026-round-3",
    sourceNote: "Round 3 date, Tarlac Circuit Hill venue, series calendar, and poster from Bike Night Asia listing.",
  },
  {
    id: "calabarzon-endurance-ride",
    title: "CALABARZON Endurance Ride",
    type: "Endurance Ride",
    status: "PUBLISHED",
    organizerId: "antipolo-endurance-challenge",
    venueId: "antipolo-endurance-start",
    poster: "/demo/poster-calabarzon-endurance-ride.jpg",
    date: "Sat · Sep 5, 2026",
    time: "5:00 AM - Sep 6 5:00 PM",
    area: "Antipolo City",
    shortDescription:
      "600KM Antipolo City motorcycle endurance challenge through the CALABARZON route.",
    whatHappens:
      "Riders check in before dawn, attend briefing, confirm route batches, ride the endurance loop, and return for finisher validation.",
    going: 52,
    interested: 168,
    expectedRiders: 90,
    perkPreview: "600KM finisher validation",
    tags: ["Endurance Ride", "CALABARZON", "600KM", "Antipolo", "Ride-out"],
    riskFlags: ["Endurance ride", "600KM route", "Overnight schedule", "Public road route"],
    rideOut: {
      meetup: "Antipolo City",
      callTime: "4:00 AM",
      departure: "5:00 AM",
      destination: "CALABARZON route",
      notes: "Tambike should require route briefing, checkpoint validation, and marshal notes for this event.",
    },
    rules: ["Helmet required", "Route briefing required", "No racing", "Follow marshals", "Check in at route points"],
    perks: [
      {
        id: "calabarzon-finisher-validation",
        type: "Validation",
        description: "Checked-in riders can be marked for 600KM finisher validation",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/ognRyNrXQ2/calabarzon-endurance-ride",
    sourceNote: "600KM route, September 5-6 dates, Antipolo start/finish, and poster from Bike Night Asia listing.",
  },
  {
    id: "laguna-motofest-2026",
    title: "Laguna MotoFest 2026",
    type: "Moto Expo",
    status: "PUBLISHED",
    organizerId: "laguna-moto-fest",
    venueId: "san-pablo-convention-center",
    poster: "/demo/poster-laguna-motofest-2026.jpg",
    date: "Sat · Oct 17, 2026",
    time: "9:00 AM - Oct 18 11:00 PM",
    area: "San Pablo City",
    shortDescription:
      "Two-day Laguna motorcycle culture event with custom showcases, brand exhibits, club meets, trade fair, and live programming.",
    whatHappens:
      "Visitors scan in at the convention center, browse displays and booths, join club networking, and save event updates for the two-day program.",
    going: 118,
    interested: 342,
    expectedRiders: 650,
    perkPreview: "Expo booth priority list",
    tags: ["Moto Expo", "Laguna", "Custom show", "Brand exhibits", "Club meets"],
    riskFlags: ["Large crowd", "Indoor queueing", "Brand activations", "Club meetups"],
    rules: ["Use assigned entrances", "Follow booth queueing", "No engine start inside halls", "Respect venue staff"],
    perks: [
      {
        id: "laguna-expo-priority",
        type: "Priority list",
        description: "Checked-in visitors can join booth and club follow-up lists",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/Z9pxDwxpDP/laguna-motofest-2026",
    sourceNote: "October 17-18 dates, San Pablo Convention Center venue, event highlights, and poster from Bike Night Asia listing.",
  },
  {
    id: "ngo-street-drag-final-2026",
    title: "NGO Street Drag Final",
    type: "Race",
    status: "PUBLISHED",
    organizerId: "ngo-philippines",
    venueId: "clark-international-speedway",
    poster: "/demo/poster-ngo-street-drag-final.jpg",
    date: "Sat · Nov 28, 2026",
    time: "8:00 AM - Nov 29 10:00 PM",
    area: "Clark, Pampanga",
    shortDescription:
      "NGO Philippines streetbike drag racing grand final at Clark International Speedway.",
    whatHappens:
      "Teams and spectators check in at Clark, follow lane and staging controls, and track final-leg updates across the two-day race weekend.",
    going: 91,
    interested: 260,
    expectedRiders: 180,
    perkPreview: "Final leg spectator pass",
    tags: ["Race", "Drag racing", "Clark", "Streetbike", "Final"],
    riskFlags: ["Drag race event", "Closed-course staging", "High crowd interest", "Pit access"],
    rules: ["Follow race marshal instructions", "Stay outside staging lanes", "No unsanctioned runs", "Use spectator areas only"],
    perks: [
      {
        id: "ngo-final-spectator-pass",
        type: "Pass",
        description: "QR spectator pass for the NGO street drag final",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/3Jpw2m3bW6/ngo-ph-street-drag-bike-party-2026-final",
    sourceNote: "November 28-29 dates, Clark International Speedway venue, streetbike drag final context, and poster from Bike Night Asia listing.",
  },
  {
    id: "ir-ph-endurance-rd3",
    title: "IR Philippine Endurance RD3",
    type: "Endurance Ride",
    status: "PUBLISHED",
    organizerId: "motoir-ph",
    venueId: "tarlac-circuit-hill",
    poster: "/demo/poster-ir-endurance-rd3.jpg",
    date: "Sat · Dec 12, 2026",
    time: "10:00 AM - Dec 13 10:00 PM",
    area: "San Jose, Tarlac",
    shortDescription:
      "IR Philippine Endurance Championships Round 3 with advance team applications and limited permanent entries.",
    whatHappens:
      "Teams submit applications before event day, check in at Tarlac Circuit Hill, verify paddock assignments, and follow endurance championship controls.",
    going: 45,
    interested: 139,
    expectedRiders: 80,
    perkPreview: "Team application tracking",
    tags: ["Endurance Ride", "Championship", "MotoIR", "Tarlac", "Team entries"],
    riskFlags: ["Endurance championship", "Advance registration", "Limited grid", "Circuit venue"],
    rules: ["Advance registration required", "No on-site registration", "Follow marshal instructions", "Respect paddock assignment"],
    perks: [
      {
        id: "ir-endurance-team-tracking",
        type: "Application tracking",
        description: "Teams can be marked for application and paddock follow-up",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/rEXjxLeby2/ir-philippine-endurance-championships-2026-rd3",
    sourceNote: "December 12-13 dates, Tarlac Circuit Hill venue, advance application details, and poster from Bike Night Asia listing.",
  },
  {
    id: "mindanao-wide-motocross-2026-2nd-leg",
    title: "Mindanao Wide Motocross 2nd Leg",
    type: "Race",
    status: "PUBLISHED",
    organizerId: "mindanao-wide-motocross",
    venueId: "wao-race-ground",
    poster: "/demo/poster-mindanao-wide-motocross-2026-2nd-leg.jpg",
    date: "Wed · Feb 18, 2026",
    time: "8:00 AM - 11:59 PM",
    area: "Wao, Lanao del Sur",
    shortDescription:
      "Second leg of the Mindanao Wide Motocross Series during the 65th Araw ng Wao celebration.",
    whatHappens:
      "Motocross teams and spectators check in at the race ground, follow staging controls, watch heats, and keep track access limited to marshaled riders.",
    going: 39,
    interested: 112,
    expectedRiders: 80,
    perkPreview: "Motocross race day pass",
    tags: ["Race", "Motocross", "Mindanao", "Wao", "Festival"],
    riskFlags: ["Motocross race", "Outdoor race site", "Spectator boundaries", "Festival crowd"],
    rules: ["Helmet required for riders", "Follow marshal instructions", "Stay outside race track", "Use assigned spectator areas"],
    perks: [
      {
        id: "mindanao-motocross-race-pass",
        type: "Pass",
        description: "QR race day pass for spectator and team check-in",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/8VXPLJwXv5/mindanao-wide-motocross-2026-2nd-leg",
    sourceNote:
      "Event name, February 18 date, Wao location, Araw ng Wao context, and poster from Bike Night Asia listing.",
  },
  {
    id: "arai-hjc-charity-ride",
    title: "ARAI HJC Charity Ride",
    type: "Charity Ride",
    status: "PENDING_ADMIN_REVIEW",
    organizerId: "arai-hjc-riders",
    venueId: "shell-pugon",
    poster: "/demo/poster-arai-hjc-charity-ride.jpg",
    date: "Sun · July 5",
    time: "7:00 AM - 5:00 PM",
    area: "Antipolo to Pililla, Rizal",
    shortDescription:
      "Helmet-user charity ride from Shell Pugon with donations for Josefheim Foundation in Pililla.",
    whatHappens:
      "Riders meet at Shell Pugon, check in, record cash or kind donations, roll out by batch, and regroup at the beneficiary stop in Pililla.",
    going: 64,
    interested: 149,
    expectedRiders: 90,
    perkPreview: "Donation drop-off at check-in",
    tags: ["Charity Ride", "Ride-out", "Donation drive", "Rizal"],
    riskFlags: ["Charity ride", "Ride-out", "Donation collection", "Public road meetup"],
    rideOut: {
      meetup: "Shell Pugon",
      callTime: "6:30 AM",
      departure: "7:00 AM",
      destination: "Josefheim Foundation, Pililla Rizal",
      notes: "Tambike tracks headcount and donation drop-off only; cash or kind donation handling stays off-app.",
    },
    rules: ["Helmet required", "Complete safety gear", "No racing", "Follow marshals", "Ride in staggered formation"],
    perks: [
      {
        id: "donation-drop",
        type: "Donation",
        description: "Donation drop-off confirmation at check-in",
      },
      {
        id: "charity-badge",
        type: "Badge",
        description: "Charity ride attendance badge after check-in",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/aRpqAQWp0k/arai-hjc-charity-ride",
    sourceNote: "Event name, date, meetup, beneficiary, safety note, and uploaded event poster from Bike Night Asia listing.",
  },
  {
    id: "ducati-track-day-clark",
    title: "Ducati Track Day",
    type: "Track Day",
    status: "PENDING_ADMIN_REVIEW",
    organizerId: "ducati-access-plus",
    venueId: "clark-international-speedway",
    poster: "/demo/poster-ducati-track-day.jpg",
    date: "Fri · July 3",
    time: "7:30 AM - 5:00 PM",
    area: "Clark, Pampanga",
    shortDescription:
      "Closed-course Ducati track day at Clark with intro lessons, test-ride bikes, and race-team technical support.",
    whatHappens:
      "Riders register for track access, pass gear inspection, attend intro lessons, request test-ride slots, and receive paddock support from the technical team.",
    going: 42,
    interested: 126,
    expectedRiders: 100,
    perkPreview: "Track intro lessons + tech support",
    tags: ["Track Day", "Brand", "Test-ride bikes", "Closed course"],
    riskFlags: ["Closed-course riding", "Gear inspection", "Test-ride bikes", "License requirement"],
    rules: [
      "Complete riding gear required",
      "Helmet required",
      "Riding jacket or leather suit required",
      "Riding gloves, pants, and boots required",
      "Test riders need Driver's License Restriction A",
    ],
    perks: [
      {
        id: "track-intro",
        type: "Training",
        description: "Free track intro lessons for checked-in riders",
      },
      {
        id: "tech-support",
        type: "Support",
        description: "Access Plus Race Team technical support at the paddock",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/YJbZogypkl/ducati-track-day",
    sourceNote: "Event name, venue, time, gear rules, test-ride bikes, and technical support from Bike Night Asia listing.",
  },
  {
    id: "long-ride-charity-zambales",
    title: "Long Ride x Charity",
    type: "Charity Ride",
    status: "PENDING_ADMIN_REVIEW",
    organizerId: "republik-riders",
    venueId: "san-marcelino-zambales",
    poster: "/demo/poster-long-ride-charity.jpg",
    date: "Sat · July 11",
    time: "3:30 AM departure",
    area: "San Marcelino, Zambales",
    shortDescription:
      "Republik Riders Club charity-focused long ride to the north with overnight route timing.",
    whatHappens:
      "Participants check in before dawn, confirm convoy batches, ride the north route, and record charity participation for the club report.",
    going: 38,
    interested: 104,
    expectedRiders: 60,
    perkPreview: "Charity convoy headcount",
    tags: ["Charity Ride", "Long ride", "Overnight", "North route"],
    riskFlags: ["Long ride", "Early departure", "Overnight schedule", "Public road convoy"],
    rideOut: {
      meetup: "San Marcelino Zambales",
      callTime: "3:00 AM",
      departure: "3:30 AM",
      destination: "North charity route",
      notes: "Extreme ride with a purpose; Tambike should require marshal notes and emergency contacts.",
    },
    rules: ["Helmet required", "Ride at legal speeds", "Confirm emergency contact", "No racing", "Stay with assigned batch"],
    perks: [
      {
        id: "charity-roster",
        type: "Roster",
        description: "Checked-in riders appear in the charity participation roster",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/LVbOZxKnjR/long-ride-x-charity",
    sourceNote: "Event name, date, location, and charity-long-ride framing from Bike Night Asia listing.",
  },
  {
    id: "mandirigma-endutour-v5",
    title: "Mandirigma Endutour V5",
    type: "Endurance Ride",
    status: "PENDING_ADMIN_REVIEW",
    organizerId: "mandirigma-endutour",
    venueId: "koronadal-city-hall",
    poster: "/demo/poster-mandirigma-endutour-v5.jpg",
    date: "Fri · July 24",
    time: "8:00 AM start",
    area: "Koronadal, South Cotabato",
    shortDescription:
      "Multi-day Mandirigma Endutour Peninsula / Ground Zero route starting from Koronadal City Hall Ground.",
    whatHappens:
      "Riders register by category, attend route briefing, scan in before release, complete checkpoints, and return with validated route logs.",
    going: 22,
    interested: 84,
    expectedRiders: 50,
    perkPreview: "Limited endurance slots",
    tags: ["Endurance Ride", "Multi-day", "Solo / Duo / Trio / Team"],
    riskFlags: ["Endurance ride", "Multi-day route", "Registration fee", "Limited route slots"],
    rideOut: {
      meetup: "Koronadal City Hall Ground",
      callTime: "7:00 AM",
      departure: "8:00 AM",
      destination: "Peninsula / Ground Zero route",
      notes: "Listing references 25 slots each for Peninsula and Ground Zero routes.",
    },
    rules: ["Helmet required", "Route briefing required", "No racing", "Carry emergency contact", "Check in at each route point"],
    perks: [
      {
        id: "route-slot",
        type: "Slot",
        description: "Confirmed rider category and route slot",
        quantity: 50,
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/yzX3vK8pEa/mandirigma-endutour-v5-2026",
    sourceNote: "Event name, dates, route category, slot limits, and Koronadal location from Bike Night Asia listing.",
  },
  {
    id: "motoir-national-round-4",
    title: "MotoIR National Round 4",
    type: "Race",
    status: "PUBLISHED",
    organizerId: "motoir-ph",
    venueId: "tarlac-circuit-hill",
    poster: "/demo/poster-motoir-round-4.jpg",
    date: "Sat · August 1",
    time: "9:00 AM",
    area: "San Jose, Tarlac",
    shortDescription:
      "MotoIR Motul National Championship Round 4 race weekend at Tarlac Circuit Hill.",
    whatHappens:
      "Spectators and teams check in at the circuit, follow pit and paddock access rules, watch scheduled heats, and receive event updates if race dates shift.",
    going: 71,
    interested: 188,
    expectedRiders: 150,
    perkPreview: "Race weekend spectator pass",
    tags: ["Race", "Circuit", "Spectator pass", "Tarlac"],
    riskFlags: ["Race event", "Circuit venue", "Pit lane access", "Schedule subject to change"],
    rules: ["Follow marshal instructions", "No hot-track access", "Stay outside pit lane barriers", "Respect posted schedule changes"],
    perks: [
      {
        id: "spectator-pass",
        type: "Pass",
        description: "QR spectator pass for race weekend entry checks",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/rEXjxg4by2/motoir-motul-national-championship-2026-round-4",
    sourceNote: "Round 4 dates, circuit venue, and schedule-change note from Bike Night Asia listing.",
  },
  {
    id: "makina-moto-expo-cebu",
    title: "Makina Moto Expo Cebu",
    type: "Moto Expo",
    status: "PUBLISHED",
    organizerId: "makina-moto",
    venueId: "ic3-cebu",
    poster: "/demo/poster-makina-moto-expo-cebu.jpg",
    date: "Fri · August 14",
    time: "8:00 AM",
    area: "Cebu City",
    shortDescription:
      "Visayas leg of Makina Moto Expo 2026 with motorcycle launches, brand booths, and rider meetups.",
    whatHappens:
      "Visitors scan in at the expo, browse motorcycle launches and gear booths, save brand-interest leads, and claim booth priority perks.",
    going: 96,
    interested: 301,
    expectedRiders: 500,
    perkPreview: "Expo booth priority list",
    tags: ["Moto Expo", "Brand", "Cebu", "Launches"],
    riskFlags: ["Large crowd", "Brand activations", "Lead collection", "Indoor queueing"],
    rules: ["Use assigned entrances", "Follow booth queueing", "No engine start inside halls", "Dealer staff handles test ride eligibility"],
    perks: [
      {
        id: "booth-priority",
        type: "Priority list",
        description: "Checked-in riders appear first on selected booth follow-up lists",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/gAn8MA1bER/makina-moto-expo-2026-cebu",
    sourceNote: "Event name, Cebu listing, and uploaded event media from Bike Night Asia.",
  },
  {
    id: "tambike-night-malabon",
    title: "Tambike Night",
    type: "Tambike",
    status: "PUBLISHED",
    organizerId: "dsboys-tambike",
    venueId: "cue-spot-cafe-malabon",
    poster: "/demo/poster-tambike-night-malabon.jpg",
    date: "Sat · May 9, 2026",
    time: "5:00 PM onwards",
    area: "Malabon",
    shortDescription:
      "Open tambike night for all motorcycle concepts at 5R Cue'Spot Cafe with clean builds and community hangout time.",
    whatHappens:
      "Riders arrive at the cafe, park by group, buy snacks or drinks onsite, compare builds, and keep the night casual with no ride-out program.",
    going: 58,
    interested: 141,
    expectedRiders: 75,
    perkPreview: "Open motorcycle meetup",
    tags: ["Tambike", "Bike night", "Open to all", "Cafe meetup"],
    riskFlags: ["Evening meetup", "Venue parking", "No engine revving"],
    rules: ["Helmet required", "No engine revving", "No slippers", "Clean as you go", "Support the venue"],
    perks: [
      {
        id: "malabon-build-spotlight",
        type: "Spotlight",
        description: "Checked-in riders can be included in the clean-build community photo set",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/ognRyONXQ2/tambike-night",
    sourceNote: "Event name, date, venue, open-to-all motorcycle framing, rules, and uploaded poster from Bike Night Asia listing.",
  },
  {
    id: "boys-underbone-laguna-tambike",
    title: "Boys of Underbone Laguna Tambike",
    type: "Tambike",
    status: "PUBLISHED",
    organizerId: "boys-underbone-laguna",
    venueId: "agojo-lifestyle-strip",
    poster: "/demo/poster-boys-underbone-laguna-tambike.jpg",
    date: "Sat · April 18, 2026",
    time: "7:00 PM onwards",
    area: "Calamba, Laguna",
    shortDescription:
      "Second official Boys of Underbone Laguna tambike built around member welcomes, content prep, and a chill hangout.",
    whatHappens:
      "Underbone riders check in at Agojo, welcome new members, prepare group content, park together, and keep the meetup casual.",
    going: 44,
    interested: 113,
    expectedRiders: 60,
    perkPreview: "Club member welcome",
    tags: ["Tambike", "Club", "Underbone", "Chill hangout"],
    riskFlags: ["Evening meetup", "Club parking", "Member onboarding"],
    rules: ["Helmet required", "No revving", "Respect venue parking", "Clean as you go"],
    perks: [
      {
        id: "underbone-member-roster",
        type: "Roster",
        description: "Checked-in riders can be tagged for member welcome and montage prep",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/zyX4BKwbQo/boys-of-underbone-laguna-chapter-2nd-official-tambike",
    sourceNote: "Event title, date, location, chill tambike agenda, and uploaded poster from Bike Night Asia listing.",
  },
  {
    id: "swabz-classic-bike-tambike",
    title: "Swabz Classic Bike Tambike",
    type: "Tambike",
    status: "PUBLISHED",
    organizerId: "swabz-classic-motoparts",
    venueId: "swabz-taytay",
    poster: "/demo/poster-swabz-classic-bike-tambike.jpg",
    date: "Sat · Jan 24, 2026",
    time: "4:00 PM onwards",
    area: "Taytay, Rizal",
    shortDescription:
      "Classic bike tambike for Swabz Taytay's grand re-opening with raffle prizes and bike consultation.",
    whatHappens:
      "Classic bike riders arrive at the shop, check in for raffle eligibility, meet other classic riders, and join the casual re-opening tambike.",
    going: 51,
    interested: 129,
    expectedRiders: 70,
    perkPreview: "Raffle + classic bike consult",
    tags: ["Tambike", "Classic bikes", "Shop event", "Raffle"],
    riskFlags: ["Shop-front parking", "Raffle list", "Classic bike crowd"],
    rules: ["Helmet required", "No revving", "Keep shop access clear", "Respect assigned parking"],
    perks: [
      {
        id: "swabz-raffle",
        type: "Raffle",
        description: "Checked-in riders join the grand re-opening raffle list",
      },
      {
        id: "classic-bike-consult",
        type: "Consultation",
        description: "Classic bike consultation queue for checked-in riders",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/d7pzZqlpK2/swabz-grand-re-opening-classic-bike-tambike",
    sourceNote: "Event name, date, Swabz Taytay location, raffle and classic bike consultation details, and poster from Bike Night Asia listing.",
  },
  {
    id: "yloco-bandits-classic-tambike",
    title: "Yloco Bandits Classic Tambike",
    type: "Tambike",
    status: "PUBLISHED",
    organizerId: "yloco-bandits",
    venueId: "bros-brew-laoag",
    poster: "/demo/poster-yloco-bandits-classic-tambike.jpg",
    date: "Sat · Jan 17, 2026",
    time: "7:00 PM onwards",
    area: "Laoag City",
    shortDescription:
      "Official 2026 classic motorcycle tambike at Bro's Brew Cafe for cafe racers, choppers, and restored classics.",
    whatHappens:
      "Classic motorcycle riders park at Bro's Brew, grab coffee, meet the Yloco Bandits, and hang out with fellow riders from the north.",
    going: 36,
    interested: 98,
    expectedRiders: 55,
    perkPreview: "Classic motorcycle meetup",
    tags: ["Tambike", "Classic bikes", "Coffee", "Laoag"],
    riskFlags: ["Evening meetup", "Cafe parking", "Classic bike display"],
    rules: ["Helmet required", "Classic motorcycles prioritized", "No revving", "Respect cafe guests"],
    perks: [
      {
        id: "classic-bike-parking",
        type: "Priority parking",
        description: "Classic motorcycles get display-side parking when space allows",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/DeXYJrvn0Z/yloco-bandits-classic-motorcycle-official-tambike",
    sourceNote: "Event name, date, Bro's Brew location, classic motorcycle scope, and uploaded poster from Bike Night Asia listing.",
  },
  {
    id: "kape-mo-to-tagaytay-tambike",
    title: "Kape Mo-To Tagaytay Tambike",
    type: "Tambike",
    status: "PUBLISHED",
    organizerId: "motor-ace-bmw",
    venueId: "kape-mo-to-tagaytay",
    poster: "/demo/poster-kape-mo-to-tagaytay-tambike.jpg",
    date: "Sat · Jan 18, 2025",
    time: "7:00 PM onwards",
    area: "Tagaytay",
    shortDescription:
      "Brand-led Kape Mo-To tambike in Tagaytay for parking, coffee, relaxed rider talk, and BMW Motorrad community presence.",
    whatHappens:
      "Riders arrive direct at Kape Mo-To, park at the motorist station, connect with other riders, and keep the activity as a stationary tambike.",
    going: 62,
    interested: 150,
    expectedRiders: 80,
    perkPreview: "Brand community meetup",
    tags: ["Tambike", "Brand", "Coffee", "Tagaytay"],
    riskFlags: ["Venue parking", "Station traffic", "Brand activation"],
    rules: ["Helmet required", "No revving", "Respect station traffic", "Park in assigned areas"],
    perks: [
      {
        id: "bmw-community-spot",
        type: "Community",
        description: "Checked-in riders can join the brand community headcount",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/LVbOZj2njR/kape-mo-to-tagaytay-tambike",
    sourceNote: "Event title, Tagaytay venue, January 18, 2025 poster date, and tambike description from Bike Night Asia listing.",
  },
  {
    id: "fullprint-manila-tambike",
    title: "FullPrint Manila Tambike",
    type: "Tambike",
    status: "PUBLISHED",
    organizerId: "fullprint-manila",
    venueId: "fullprint-manila-cafe",
    poster: "/demo/poster-fullprint-manila-tambike.jpg",
    date: "Sat · Oct 5, 2024",
    time: "7:00 AM onwards",
    area: "Paranaque",
    shortDescription:
      "Morning FullPrint Manila tambike with Segway Escooters, Triumph Motorcycles, and free breakfast for early riders.",
    whatHappens:
      "Riders and e-scooter owners arrive at the cafe, check in for the breakfast headcount, browse partner displays, and hang out onsite.",
    going: 57,
    interested: 118,
    expectedRiders: 75,
    perkPreview: "Free breakfast first 50",
    tags: ["Tambike", "Breakfast", "Cafe", "Brand partners"],
    riskFlags: ["Morning meetup", "Breakfast quantity", "Storefront parking"],
    rules: ["Helmet required", "Keep storefront clear", "No revving", "Respect cafe guests"],
    perks: [
      {
        id: "fullprint-breakfast",
        type: "Food",
        description: "Free breakfast queue for the first 50 checked-in riders",
        quantity: 50,
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/4DnB0V3p5m/full-print-manila-tambike",
    sourceNote: "Event name, date, FullPrint Manila Cafe location, first-50 breakfast perk, and poster from Bike Night Asia listing.",
  },
  {
    id: "boys-garage-crossmeet-tambike",
    title: "Boys of Garage Crossmeet Tambike",
    type: "Tambike",
    status: "PUBLISHED",
    organizerId: "boys-of-garage",
    venueId: "dayo-specialty-coffee",
    poster: "/demo/poster-boys-garage-crossmeet-tambike.jpg",
    date: "Sun · Mar 22, 2026",
    time: "8:00 PM onwards",
    area: "Quezon City",
    shortDescription:
      "Cross-club tambike for a cause at Dayo Specialty Coffee with Boys of Garage, 2 Wheels Elite, Boys of Congre, and BB Boyz.",
    whatHappens:
      "Riders meet at the coffee spot, park with their groups, support the cause, and keep the night stationary with no stunts, racing, or loud revving.",
    going: 46,
    interested: 121,
    expectedRiders: 70,
    perkPreview: "Cause meetup headcount",
    tags: ["Tambike", "Crossmeet", "Coffee", "For a cause"],
    riskFlags: ["Evening meetup", "Cross-club crowd", "Cause headcount", "Venue parking"],
    rules: ["Helmet required", "No littering", "No burnouts", "No stunts or wheelies", "No aggressive revving"],
    perks: [
      {
        id: "crossmeet-headcount",
        type: "Roster",
        description: "Checked-in riders count toward the crossmeet cause attendance list",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/3Jpw2xAbW6/boys-of-garage-crossmeet-tambike",
    sourceNote: "Event name, date, Dayo Specialty Coffee location, cause framing, rules, and uploaded poster from Bike Night Asia listing.",
  },
  {
    id: "ccph-upper-east-tambike",
    title: "CCPH Upper East Tambike",
    type: "Tambike",
    status: "PUBLISHED",
    organizerId: "ccph-upper-east",
    venueId: "helmet-garage-cainta",
    poster: "/demo/poster-ccph-upper-east-tambike.jpg",
    date: "Sat · Oct 4, 2025",
    time: "4:00 PM onwards",
    area: "Cainta, Rizal",
    shortDescription:
      "CCPH Upper East first tambike at The Helmet Garage with safe moto rules and raffle registration.",
    whatHappens:
      "Riders pin the shop location, register onsite for raffles, park with the chapter, and follow safe tambike rules around the venue.",
    going: 53,
    interested: 137,
    expectedRiders: 80,
    perkPreview: "Raffle registration",
    tags: ["Tambike", "Club", "Moto shop", "Raffle"],
    riskFlags: ["Shop-front parking", "Raffle list", "Chapter meetup"],
    rules: ["Helmet required", "No revving", "No littering", "No burnouts or wheelies", "No aggressive driving"],
    perks: [
      {
        id: "upper-east-raffle",
        type: "Raffle",
        description: "Checked-in riders can be listed for onsite raffle registration",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/ZJprwqPXaE/ccph-upper-east-1st-tambike",
    sourceNote: "Event name, date, The Helmet Garage Cainta location, raffle registration note, rules, and poster from Bike Night Asia listing.",
  },
  {
    id: "ccph-cebu-official-tambike",
    title: "CCPH Cebu Official Tambike",
    type: "Tambike",
    status: "PUBLISHED",
    organizerId: "ccph-cebu",
    venueId: "mactan-town-center",
    poster: "/demo/poster-ccph-cebu-official-tambike.jpg",
    date: "Sat · Nov 29, 2025",
    time: "7:00 PM onwards",
    area: "Lapu-Lapu City",
    shortDescription:
      "CCPH Cebu third official tambike at Mactan Town Center with chapter rollup rules and venue-respect reminders.",
    whatHappens:
      "Cebu riders arrive at Mactan Town Center, group by chapter, check in, and keep the meetup focused on parked bikes and community.",
    going: 49,
    interested: 116,
    expectedRiders: 75,
    perkPreview: "Chapter rollup list",
    tags: ["Tambike", "Cebu", "Club", "Chapter rollup"],
    riskFlags: ["Evening meetup", "Commercial venue", "Chapter parking"],
    rules: ["Helmet required", "No pops and bangs", "No slippers", "No loitering", "No showboating"],
    perks: [
      {
        id: "ccph-cebu-rollup",
        type: "Roster",
        description: "Checked-in riders appear in the CCPH Cebu chapter rollup list",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/ZJprwReXaE/ccph-cebu-3rd-official-tambike",
    sourceNote: "Event name, date, Mactan Town Center venue, rules, and uploaded poster from Bike Night Asia listing.",
  },
];

export const venueApproval: Approval = {
  id: "req-shell-pugon",
  eventId: "arai-hjc-charity-ride",
  type: "venue",
  decision: "pending",
  reviewer: "Shell Pugon staff",
  notes: "Pending driveway staging, donation drop-off table, and batch departure conditions.",
};

export const adminApproval: Approval = {
  id: "rev-arai-hjc-charity-ride",
  eventId: "arai-hjc-charity-ride",
  type: "admin",
  decision: "pending",
  reviewer: "Tambike ops",
  notes: "Review donation collection, public road ride-out, and beneficiary coordination.",
};

export const defaultPass: Pass = {
  id: "pass-tambike-cafe-classico",
  eventId: "tambike-cafe-classico",
  qrToken: "pass_tambike_cafe_classico",
  status: "active",
  generatedAt: "July 2, 2026 · 8:12 AM",
};

export const reportMetrics: ReportMetric[] = [
  { label: "Interested", value: "132", detail: "Saved or shared before tambike night" },
  { label: "Going", value: "48", detail: "QR passes generated" },
  { label: "Check-ins", value: "41", detail: "Scanned or manually marked" },
  { label: "No-show rate", value: "15%", detail: "Going vs actual check-ins" },
  { label: "Perk redemptions", value: "24", detail: "Coffee discount claims" },
  { label: "Peak arrival", value: "6:42 PM", detail: "Most check-ins during first hour" },
];

export function getEvent(eventId?: string) {
  return demoEvents.find((event) => event.id === eventId) ?? demoEvents[0];
}

export function getVenue(venueId?: string) {
  return venues.find((venue) => venue.id === venueId) ?? venues[0];
}

export function getOrganizer(organizerId?: string) {
  return organizers.find((organizer) => organizer.id === organizerId) ?? organizers[0];
}
