import type {
  Approval,
  Event,
  OrganizerProfile,
  Pass,
  ReportMetric,
  UserProfile,
  Venue,
} from "./types";

export const venues: Venue[] = [
  {
    id: "casa-classico",
    name: "Casa Classico",
    area: "Davao City",
    address: "Casa Classico, Manga St., Tugbok, Davao City",
    mapLink: "https://waze.com/ul?q=Casa%20Classico%20Davao%20City",
    capacityNote: "Small recurring tambike spot for coffee, parking, and casual rider hangouts.",
    status: "APPROVED",
    houseRules: ["Park in assigned areas", "No revving", "Respect cafe guests"],
  },
  {
    id: "shell-pugon",
    name: "Shell Pugon",
    area: "Antipolo",
    address: "Shell Pugon, City of Antipolo, Rizal",
    mapLink: "https://waze.com/ul?q=Shell%20Pugon%20Antipolo",
    capacityNote: "Meetup point for charity and Marilaque-bound ride groups.",
    status: "APPROVED",
    houseRules: ["Keep pumps and driveway clear", "Stage by batch", "No revving"],
  },
  {
    id: "clark-international-speedway",
    name: "Clark International Speedway",
    area: "Angeles City",
    address: "Clark International Speedway, Angeles City, Pampanga",
    mapLink: "https://waze.com/ul?q=Clark%20International%20Speedway",
    capacityNote: "Closed-course track venue with paddock and technical support areas.",
    status: "APPROVED",
    houseRules: ["Complete riding gear required", "Track staff controls entry", "Follow paddock flow"],
  },
  {
    id: "san-marcelino-zambales",
    name: "San Marcelino Ride Base",
    area: "Zambales",
    address: "San Marcelino, Zambales",
    mapLink: "https://waze.com/ul?q=San%20Marcelino%20Zambales",
    capacityNote: "Municipality-level meetup marker for long-ride coordination.",
    status: "APPROVED",
    houseRules: ["Arrive fueled", "Confirm emergency contacts", "Depart by ride marshal signal"],
  },
  {
    id: "koronadal-city-hall",
    name: "Koronadal City Hall Ground",
    area: "Koronadal",
    address: "Koronadal City Hall Ground, Koronadal City, South Cotabato",
    mapLink: "https://waze.com/ul?q=Koronadal%20City%20Hall%20Ground",
    capacityNote: "Event ground for multi-day endurance ride registration and dispatch.",
    status: "APPROVED",
    houseRules: ["Check in before route briefing", "Respect slot limits", "No unsanctioned departures"],
  },
  {
    id: "tarlac-circuit-hill",
    name: "Tarlac Circuit Hill",
    area: "San Jose, Tarlac",
    address: "Tarlac Circuit Hill, San Jose, Tarlac",
    mapLink: "https://waze.com/ul?q=Tarlac%20Circuit%20Hill",
    capacityNote: "Circuit venue for race weekends and spectator check-in.",
    status: "APPROVED",
    houseRules: ["Observe pit lane boundaries", "Follow marshal instructions", "No access to hot track"],
  },
  {
    id: "ic3-cebu",
    name: "IC3 Convention Center Cebu",
    area: "Cebu City",
    address: "IC3 Convention Center, Cebu City",
    mapLink: "https://waze.com/ul?q=IC3%20Convention%20Center%20Cebu",
    capacityNote: "Indoor expo venue suited for brand booths, launches, and rider meetups.",
    status: "APPROVED",
    houseRules: ["Use assigned entrances", "Follow booth queueing", "No engine start inside halls"],
  },
];

export const organizers: OrganizerProfile[] = [
  {
    id: "cafe-classico",
    displayName: "Cafe Classico Davao",
    type: "Cafe tambike host",
    fbLink: "facebook.com/share/1CpR9D1nwL",
    verificationStatus: "APPROVED",
    pastEvents: 6,
  },
  {
    id: "arai-hjc-riders",
    displayName: "ARAI / HJC Riders PH",
    type: "Helmet-user charity ride community",
    fbLink: "facebook.com/groups/helmetridersph",
    verificationStatus: "APPROVED",
    pastEvents: 2,
  },
  {
    id: "ducati-access-plus",
    displayName: "Ducati Philippines / Access Plus",
    type: "Brand and track organizer",
    fbLink: "facebook.com/DucatiPhilippines",
    verificationStatus: "APPROVED",
    pastEvents: 14,
  },
  {
    id: "republik-riders",
    displayName: "Republik Riders Club",
    type: "Motorcycle charity ride club",
    fbLink: "facebook.com/republikridersclub",
    verificationStatus: "APPROVED",
    pastEvents: 5,
  },
  {
    id: "mandirigma-endutour",
    displayName: "Mandirigma Endutour",
    type: "Endurance ride organizer",
    fbLink: "facebook.com/mandirigmaendutour",
    verificationStatus: "APPROVED",
    pastEvents: 4,
  },
  {
    id: "motoir-ph",
    displayName: "MotoIR Philippines",
    type: "Motorcycle race organizer",
    fbLink: "facebook.com/motoirph",
    verificationStatus: "APPROVED",
    pastEvents: 24,
  },
  {
    id: "makina-moto",
    displayName: "Makina Moto",
    type: "Motorcycle expo organizer",
    fbLink: "facebook.com/makinamotoph",
    verificationStatus: "APPROVED",
    pastEvents: 12,
  },
];

export const mockUsers: UserProfile[] = [
  {
    id: "user-mina-rider",
    displayName: "Mina Rider",
    email: "mina.rider@example.com",
    role: "rider",
    verificationStatus: "UNVERIFIED",
    area: "Marikina",
    bikeModel: "Yamaha Mio Gear",
    clubName: "Weekend Tambike Crew",
    joinedAt: "July 2, 2026",
  },
  {
    id: "user-marco-organizer",
    displayName: "Marco Organizer",
    email: "marco.organizer@example.com",
    role: "organizer",
    verificationStatus: "APPROVED",
    area: "Antipolo",
    bikeModel: "Honda CB650R",
    clubName: "ARAI / HJC Riders PH",
    joinedAt: "June 18, 2026",
    organizerProfileId: "arai-hjc-riders",
  },
  {
    id: "user-ana-venue",
    displayName: "Ana Venue",
    email: "ana.venue@example.com",
    role: "venue",
    verificationStatus: "APPROVED",
    area: "Antipolo",
    joinedAt: "June 24, 2026",
    venueId: "shell-pugon",
  },
  {
    id: "user-tambike-ops",
    displayName: "Tambike Ops",
    email: "ops@tambike.example",
    role: "admin",
    verificationStatus: "APPROVED",
    area: "Metro Manila",
    joinedAt: "June 1, 2026",
  },
];

export const demoEvents: Event[] = [
  {
    id: "tambike-cafe-classico",
    title: "Tambike at Cafe Classico",
    type: "Tambike",
    status: "PUBLISHED",
    organizerId: "cafe-classico",
    venueId: "casa-classico",
    poster: "/demo/poster-tambike-cafe-classico.jpg",
    date: "Every Saturday",
    time: "6:00 PM - 8:00 PM",
    area: "Davao City",
    shortDescription:
      "A recurring Saturday tambike for classic bikes, coffee, stories, and relaxed rider hangouts.",
    whatHappens:
      "Riders arrive direct at Casa Classico, park, check in, grab coffee, talk bikes, and hang out without a ride-out or formal program.",
    going: 48,
    interested: 132,
    expectedRiders: 55,
    perkPreview: "10% coffee discount",
    tags: ["Tambike", "Coffee", "Classic bikes", "No ride-out"],
    riskFlags: ["Evening meetup", "Venue parking", "Coffee discount"],
    rules: ["Helmet required", "No revving", "Respect cafe guests", "Park in assigned areas"],
    perks: [
      {
        id: "classic-coffee-discount",
        type: "Discount",
        description: "10% coffee discount for classic motorcycle owners from 6 PM to 8 PM",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/RwX2gPAndM/tambike-at-cafe-classico-every-saturday",
    sourceNote: "Event name, recurring Saturday tambike format, venue, time, and coffee discount from Bike Night Asia listing.",
  },
  {
    id: "arai-hjc-charity-ride",
    title: "ARAI HJC Charity Ride",
    type: "Charity Ride",
    status: "PENDING_ADMIN_REVIEW",
    organizerId: "arai-hjc-riders",
    venueId: "shell-pugon",
    poster: "/demo/poster-arai-hjc-charity-ride.jpg",
    date: "Sun · July 5",
    time: "7:00 AM - 5:00 PM",
    area: "Antipolo to Pililla, Rizal",
    shortDescription:
      "Helmet-user charity ride from Shell Pugon with donations for Josefheim Foundation in Pililla.",
    whatHappens:
      "Riders meet at Shell Pugon, check in, record cash or kind donations, roll out by batch, and regroup at the beneficiary stop in Pililla.",
    going: 64,
    interested: 149,
    expectedRiders: 90,
    perkPreview: "Donation drop-off at check-in",
    tags: ["Charity Ride", "Ride-out", "Donation drive", "Rizal"],
    riskFlags: ["Charity ride", "Ride-out", "Donation collection", "Public road meetup"],
    rideOut: {
      meetup: "Shell Pugon",
      callTime: "6:30 AM",
      departure: "7:00 AM",
      destination: "Josefheim Foundation, Pililla Rizal",
      notes: "Tambike tracks headcount and donation drop-off only; cash or kind donation handling stays off-app.",
    },
    rules: ["Helmet required", "Complete safety gear", "No racing", "Follow marshals", "Ride in staggered formation"],
    perks: [
      {
        id: "donation-drop",
        type: "Donation",
        description: "Donation drop-off confirmation at check-in",
      },
      {
        id: "charity-badge",
        type: "Badge",
        description: "Charity ride attendance badge after check-in",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/aRpqAQWp0k/arai-hjc-charity-ride",
    sourceNote: "Event name, date, meetup, beneficiary, safety note, and uploaded event poster from Bike Night Asia listing.",
  },
  {
    id: "ducati-track-day-clark",
    title: "Ducati Track Day",
    type: "Track Day",
    status: "PENDING_ADMIN_REVIEW",
    organizerId: "ducati-access-plus",
    venueId: "clark-international-speedway",
    poster: "/demo/poster-ducati-track-day.jpg",
    date: "Fri · July 3",
    time: "7:30 AM - 5:00 PM",
    area: "Clark, Pampanga",
    shortDescription:
      "Closed-course Ducati track day at Clark with intro lessons, demo bikes, and race-team technical support.",
    whatHappens:
      "Riders register for track access, pass gear inspection, attend intro lessons, request demo-bike slots, and receive paddock support from the technical team.",
    going: 42,
    interested: 126,
    expectedRiders: 100,
    perkPreview: "Track intro lessons + tech support",
    tags: ["Track Day", "Brand", "Demo bikes", "Closed course"],
    riskFlags: ["Closed-course riding", "Gear inspection", "Demo bikes", "License requirement"],
    rules: [
      "Complete riding gear required",
      "Helmet required",
      "Riding jacket or leather suit required",
      "Riding gloves, pants, and boots required",
      "Test riders need Driver's License Restriction A",
    ],
    perks: [
      {
        id: "track-intro",
        type: "Training",
        description: "Free track intro lessons for checked-in riders",
      },
      {
        id: "tech-support",
        type: "Support",
        description: "Access Plus Race Team technical support at the paddock",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/YJbZogypkl/ducati-track-day",
    sourceNote: "Event name, venue, time, gear rules, demo bikes, and technical support from Bike Night Asia listing.",
  },
  {
    id: "long-ride-charity-zambales",
    title: "Long Ride x Charity",
    type: "Charity Ride",
    status: "PENDING_ADMIN_REVIEW",
    organizerId: "republik-riders",
    venueId: "san-marcelino-zambales",
    poster: "/demo/poster-long-ride-charity.jpg",
    date: "Sat · July 11",
    time: "3:30 AM departure",
    area: "San Marcelino, Zambales",
    shortDescription:
      "Republik Riders Club charity-focused long ride to the north with overnight route timing.",
    whatHappens:
      "Participants check in before dawn, confirm convoy batches, ride the north route, and record charity participation for the club report.",
    going: 38,
    interested: 104,
    expectedRiders: 60,
    perkPreview: "Charity convoy headcount",
    tags: ["Charity Ride", "Long ride", "Overnight", "North route"],
    riskFlags: ["Long ride", "Early departure", "Overnight schedule", "Public road convoy"],
    rideOut: {
      meetup: "San Marcelino Zambales",
      callTime: "3:00 AM",
      departure: "3:30 AM",
      destination: "North charity route",
      notes: "Extreme ride with a purpose; Tambike should require marshal notes and emergency contacts.",
    },
    rules: ["Helmet required", "Ride at legal speeds", "Confirm emergency contact", "No racing", "Stay with assigned batch"],
    perks: [
      {
        id: "charity-roster",
        type: "Roster",
        description: "Checked-in riders appear in the charity participation roster",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/LVbOZxKnjR/long-ride-x-charity",
    sourceNote: "Event name, date, location, and charity-long-ride framing from Bike Night Asia listing.",
  },
  {
    id: "mandirigma-endutour-v5",
    title: "Mandirigma Endutour V5",
    type: "Endurance Ride",
    status: "PENDING_ADMIN_REVIEW",
    organizerId: "mandirigma-endutour",
    venueId: "koronadal-city-hall",
    poster: "/demo/poster-mandirigma-endutour-v5.jpg",
    date: "Fri · July 24",
    time: "8:00 AM start",
    area: "Koronadal, South Cotabato",
    shortDescription:
      "Multi-day Mandirigma Endutour Peninsula / Ground Zero route starting from Koronadal City Hall Ground.",
    whatHappens:
      "Riders register by category, attend route briefing, scan in before release, complete checkpoints, and return with validated route logs.",
    going: 22,
    interested: 84,
    expectedRiders: 50,
    perkPreview: "Limited endurance slots",
    tags: ["Endurance Ride", "Multi-day", "Solo / Duo / Trio / Team"],
    riskFlags: ["Endurance ride", "Multi-day route", "Registration fee", "Limited route slots"],
    rideOut: {
      meetup: "Koronadal City Hall Ground",
      callTime: "7:00 AM",
      departure: "8:00 AM",
      destination: "Peninsula / Ground Zero route",
      notes: "Listing references 25 slots each for Peninsula and Ground Zero routes.",
    },
    rules: ["Helmet required", "Route briefing required", "No racing", "Carry emergency contact", "Check in at each route point"],
    perks: [
      {
        id: "route-slot",
        type: "Slot",
        description: "Confirmed rider category and route slot",
        quantity: 50,
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/yzX3vK8pEa/mandirigma-endutour-v5-2026",
    sourceNote: "Event name, dates, route category, slot limits, and Koronadal location from Bike Night Asia listing.",
  },
  {
    id: "motoir-national-round-4",
    title: "MotoIR National Round 4",
    type: "Race",
    status: "PUBLISHED",
    organizerId: "motoir-ph",
    venueId: "tarlac-circuit-hill",
    poster: "/demo/poster-motoir-round-4.jpg",
    date: "Sat · August 1",
    time: "9:00 AM",
    area: "San Jose, Tarlac",
    shortDescription:
      "MotoIR Motul National Championship Round 4 race weekend at Tarlac Circuit Hill.",
    whatHappens:
      "Spectators and teams check in at the circuit, follow pit and paddock access rules, watch scheduled heats, and receive event updates if race dates shift.",
    going: 71,
    interested: 188,
    expectedRiders: 150,
    perkPreview: "Race weekend spectator pass",
    tags: ["Race", "Circuit", "Spectator pass", "Tarlac"],
    riskFlags: ["Race event", "Circuit venue", "Pit lane access", "Schedule subject to change"],
    rules: ["Follow marshal instructions", "No hot-track access", "Stay outside pit lane barriers", "Respect posted schedule changes"],
    perks: [
      {
        id: "spectator-pass",
        type: "Pass",
        description: "QR spectator pass for race weekend entry checks",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/rEXjxg4by2/motoir-motul-national-championship-2026-round-4",
    sourceNote: "Round 4 dates, circuit venue, and schedule-change note from Bike Night Asia listing.",
  },
  {
    id: "makina-moto-expo-cebu",
    title: "Makina Moto Expo Cebu",
    type: "Moto Expo",
    status: "PUBLISHED",
    organizerId: "makina-moto",
    venueId: "ic3-cebu",
    poster: "/demo/poster-makina-moto-expo-cebu.jpg",
    date: "Fri · August 14",
    time: "8:00 AM",
    area: "Cebu City",
    shortDescription:
      "Visayas leg of Makina Moto Expo 2026 with motorcycle launches, brand booths, and rider meetups.",
    whatHappens:
      "Visitors scan in at the expo, browse motorcycle launches and gear booths, save brand-interest leads, and claim booth priority perks.",
    going: 96,
    interested: 301,
    expectedRiders: 500,
    perkPreview: "Expo booth priority list",
    tags: ["Moto Expo", "Brand", "Cebu", "Launches"],
    riskFlags: ["Large crowd", "Brand activations", "Lead capture", "Indoor queueing"],
    rules: ["Use assigned entrances", "Follow booth queueing", "No engine start inside halls", "Dealer staff handles test ride eligibility"],
    perks: [
      {
        id: "booth-priority",
        type: "Priority list",
        description: "Checked-in riders appear first on selected booth follow-up lists",
      },
    ],
    sourceUrl: "https://bikenightasia.com/events/view/gAn8MA1bER/makina-moto-expo-2026-cebu",
    sourceNote: "Event name, Cebu listing, and uploaded event media from Bike Night Asia.",
  },
];

export const venueApproval: Approval = {
  id: "req-shell-pugon",
  eventId: "arai-hjc-charity-ride",
  type: "venue",
  decision: "pending",
  reviewer: "Shell Pugon staff",
  notes: "Pending driveway staging, donation drop-off table, and batch departure conditions.",
};

export const adminApproval: Approval = {
  id: "rev-arai-hjc-charity-ride",
  eventId: "arai-hjc-charity-ride",
  type: "admin",
  decision: "pending",
  reviewer: "Tambike ops",
  notes: "Review donation collection, public road ride-out, and beneficiary coordination.",
};

export const defaultPass: Pass = {
  id: "pass-tambike-cafe-classico",
  eventId: "tambike-cafe-classico",
  qrToken: "TBK-TAMBIKE-CAFE-CLASSICO",
  status: "active",
  generatedAt: "July 2, 2026 · 8:12 AM",
};

export const reportMetrics: ReportMetric[] = [
  { label: "Interested", value: "132", detail: "Saved or shared before tambike night" },
  { label: "Going", value: "48", detail: "QR passes generated" },
  { label: "Check-ins", value: "41", detail: "Scanned or manually marked" },
  { label: "No-show rate", value: "15%", detail: "Going vs actual check-ins" },
  { label: "Perk redemptions", value: "24", detail: "Coffee discount claims" },
  { label: "Peak arrival", value: "6:42 PM", detail: "Most check-ins during first hour" },
];

export function getEvent(eventId?: string) {
  return demoEvents.find((event) => event.id === eventId) ?? demoEvents[0];
}

export function getVenue(venueId?: string) {
  return venues.find((venue) => venue.id === venueId) ?? venues[0];
}

export function getOrganizer(organizerId?: string) {
  return organizers.find((organizer) => organizer.id === organizerId) ?? organizers[0];
}
